#!/usr/bin/env python3

from flask import Flask, make_response, request
import json
import re
import requests

import os
import datetime

app = Flask(__name__)

@app.route('/realtimedeparturesV4')
def index():

    apiKey = request.args.get('apiKey')
    destinationFilter = request.args.get('destinationFilter')
    stationId = request.args.get('stationId')
    transportMode = request.args.get('transportMode')

    if not apiKey:
        today = datetime.datetime.today().weekday()
        selector = None

        if today == 0:
            selector = "MONDAY"
        elif today == 1:
            selector = "TUESDAY"
        elif today == 2:
            selector = "WEDNESDAY"
        elif today == 3:
            selector = "THURSDAY"
        elif today == 4:
            selector = "FRIDAY"
        elif today == 5:
            selector = "SATURDAY"
        elif today == 6:
            selector = "SUNDAY"
        apiKey = os.environ.get(selector)


    API_BASE_URL = 'https://api.sl.se/api2/realtimedeparturesV4.json'
    url = API_BASE_URL + "?key=" + apiKey + "&siteid=" + str(stationId)

    res = requests.get(url)
    if res.status_code == 200:
        result = res.json()
    else:
        raise Error('Error: ' + str(res.status_code) +  str(res.content))

    list = []
    for entry in result['ResponseData'][transportMode]:
        destination = entry['Destination']
        displayTime = entry['DisplayTime']
        if destinationFilter:
            pattern = "^(" + destinationFilter + ")"
            if re.match(pattern, destination, re.IGNORECASE):
                list.append(destination + " " + displayTime)
        else:
            list.append(destination + " " + displayTime)

    json_data = json.dumps({"departures": list})
    response = make_response(json_data)
    response.headers['Content-Type'] = 'application/json'
    return response

if __name__ == "__main__":
    app.run(host='0.0.0.0')
